services:
  order-generator-api:
    build:
      context: .
      dockerfile: src/OrderGenerator/OrderGenerator.API/Dockerfile
    ports:
      - "5159:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db-ordergenerator;Port=5432;Database=orderdb;Username=postgres;Password=postgres
    depends_on:
      - db-ordergenerator

  order-accumulator-api:
    build:
      context: .
      dockerfile: src/OrderAccumulator/OrderAccumulator.API/Dockerfile
    ports:
      - "64164:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db-orderaccumulator;Port=5432;Database=orderaccumulator;Username=postgres;Password=postgres
    depends_on:
      - db-orderaccumulator

  order-generator-ui:
    build:
      context: .
      dockerfile: src/order-generator/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - order-generator-api
      - order-accumulator-api

  db-ordergenerator:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_ordergenerator:/var/lib/postgresql/data

  db-orderaccumulator:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderaccumulator
    ports:
      - "5434:5432"
    volumes:
      - pgdata_orderaccumulator:/var/lib/postgresql/data

volumes:
  pgdata_ordergenerator:
  pgdata_orderaccumulator:
